name: compile
run-name: Compilation of webapp for windows
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --save-dev electron
        run: npm install --save-dev @electron-forge/cli
        run: npx electron-forge import
      - name: Compi
        run: npm run make
