name: compile
run-name: Compilation of webapp for windows
on: 
  push:
    branches: [release]

jobs:
  compilation:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setupping node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: "npm"
      - name: Installing electron
        run: npm install --save-dev electron @electron-forge/cli
      - name: Finalizing electron installation
        run: npx electron-forge import
      - name: Compilling
        run: npm run make
      - name: Zipping files
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: './out/dsc-blockchain-alpha-win32-x64'
          filename: 'release-win64.zip'
      - uses: actions/upload-artifact@v3
        with:
          name: 'win'
          path: 'release-win64.zip'
