name: compile
run-name: Compilation of webapp for macos
on:
  push:
    branches: [main]

jobs:
  compilation:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm cache add @electron-forge/cli
      - run: npm install @electron-forge/cli
      - run: npx electron-forge import
      - run: npm run make
