name: compile
run-name: Compilation of webapp for windows
on: 
  push:
    branches: [release]

jobs:
  compilation:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setupping node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: "npm"
      - name: Installing electron
        run: npm install --save-dev electron @electron-forge/cli
      - name: Finalizing electron installation
        run: npx electron-forge import
      - name: Compilling
        run: npm run make
      - name: Zipping files
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release-win64.zip"
          directory: .\out\dsc-blockchain-alpha-win32-x64
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Uploading release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.run_number }} - Windows x64
          artifacts: "release-win64.zip"
