name: compile
run-name: Compilation of webapp for windows
on:
  push:
    branches:
      - release

jobs:
  dependency-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: npm install --save-dev electron @electron-forge/cli
      - run: npx electron-forge import
      - run: npm run make
