name: compile
run-name: Compilation of webapp for windows
on: 
  push:
    branches: [release]

jobs:
  compilation:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setupping node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Installing electron
        run: npm install --save-dev electron @electron-forge/cli
      - name: Finalizing electron installation
        run: npx electron-forge import
      - name: Compilling
        run: npm run make
      - name: Publishing release
        uses: ColinPitrat/update-release@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./out/make/squirrel.windows/x64/dsc-blockchain-alpha-1.0.0/Setup.exe
